management:
  endpoints:
    web:
      exposure:
        include: health,env,info,configprops
logging:
  group:
    test: 
      com.example.demo
server:
  port: 8080
spring:
  application:
    name: standard


  

