management:
  endpoints:
    web:
      exposure:
        include: health,env,info,configprops,loggers,refresh
logging:
  group:
    test: 
      com.example.demo
server:
  port: 8080
spring:
  application:
    name: standard
config:
  property: 0711

  

